version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            apt-get update
            apt-get install -y software-properties-common
            apt-get install -y apt-transport-https ca-certificates
            apt-get update
            apt-get install make
            apt-get install -y wget
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
            apt-get install -y \
              curl \
              gnupg-agent
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              bionic \
              stable"
            apt-get update
            apt-get install -y docker-ce docker-ce-cli containerd.io
            ./setup.sh
            pip install pylint
      - run:
          name: Lint
          command: |
            source activate capstone
            make lint
      - run:
          name: Container
          command: |
            make container
