version: 2
executors:
  hadolint_executor:
    parameters:
      tag:
        type: string
        default: "v1.6.6-6-g254b4ff"
    docker:
      - image: hadolint/hadolint:<<parameters.tag>>
jobs:
  dockerfile_lint:
    executor: hadolint_executor
    steps:
      - run_dockerfile_lint
  build:
    docker:
      - image: jjahs/capstone:latest
    steps:
      - checkout
    # run lint!
      - run:
          name: run lint
          command: |
            make lint
