version: 2.1
jobs:
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          #https://github.com/ahernandezsouza/devops-capstone
          name: Pull Code
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            make
