version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            apt-get update
            apt-get install -y software-properties-common
            apt-get install -y apt-transport-https ca-certificates
            apt-get update
            apt-get install make
            apt-get install -y wget
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
            apt-get install -y gnupg
            apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
            apt-add-repository 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
            apt-get update
            apt-get install -y docker-engine
            ./setup.sh
            pip install pylint
      - run:
          name: Lint
          command: |
            source activate capstone
            make lint
      - run:
          name: Container
          command: |
            make container
