 version: 2
 jobs:
   build:
     docker:
       - image: jjahs/capstone:latest
     steps:
       - checkout
       - run:
          name: install dependencies
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
      # run lint!
       - run:
          name: run lint
          command: |
            make lint
