version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:xenial-20200212
    steps:
      - checkout
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Lint
          command: |
            apt-get update
            apt-get install make
            make lint
