version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build-and-lint:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Build
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
            apt-get update
            apt-get install -y software-properties-common
            apt-get install -y apt-transport-https ca-certificates
            apt-get update
            apt-get install make
            apt-get install -y wget
            apt-get install -y jq
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
            apt-get install -y \
              curl \
              gnupg-agent
            ./setup.sh
            pip install pylint
      - run:
          name: Lint
          command: |
            source activate capstone
            make lint

      - setup_remote_docker
      - docker/install-docker-tools
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jjahs/capstone:$TAG .
          echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
          docker push jjahs/capstone:$TAG

  #build-and-push:
    #machine: true
    #steps:
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      #- run: |
      #    echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin

      # build the application image
      #- run: docker build -f /home/circleci/project/Dockerfile /home/circleci/project -t jjahs/capstone:latest

      # deploy the image
      #- run: docker push jjahs/capstone:latest
workflows:
  setup:
    jobs:
      - build-and-lint
      #- build-and-push:
      #    requires:
      #      - build-and-lint
